<?php
header('Content-Type: application/pdf');
header('Content-Disposition: inline; filename=output.pdf');

echo '%PDF-1.3
1 0 obj
<< /Type /Catalog
/Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages
/Kids [3 0 R]
/Count 1 >>
endobj
3 0 obj
<< /Type /Page
/Parent 2 0 R
/MediaBox [0 0 612 792]
/Resources << /Font << /F1 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> >> >>
/Contents 4 0 R >>
endobj
4 0 obj
<< /Length 45 >>
stream
BT
/F1 18 Tf
100 100 Td
(Hello, this is a PDF document generated by PHP) Tj
ET
endstream
endobj
xref
0 5
0000000000 65535 f 
0000000018 00000 n 
0000000077 00000 n 
0000000178 00000 n 
0000000458 00000 n 
trailer
<< /Root 1 0 R
/Size 5 >>
startxref
546
%%EOF
';
?>